language: d
d: dmd
sudo: required
dist: trusty
env:
  - VERSION=1.0.8
before_install:
  - curl https://download.libsodium.org/libsodium/releases/libsodium-$VERSION.tar.gz | tar -C ~ -xzf -
  - pushd ~/libsodium-$VERSION
  - ./configure --prefix=/usr && make && sudo make install
  - popd
